### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by lukaslueg** [LukasKalbertodt/bunt#12]
Not an issue, just a question: What's the reason for using this `match` construct instead of a simple `if elseif else`. There are no new bindings and the compiler can't help with the patterns...

https://github.com/LukasKalbertodt/bunt/blob/91a65fbb33f7c79d5b63f901c4b2f0106e68393d/macros/src/parse/fmt.rs#L61-L81

**Comment by LukasKalbertodt** [comment]
It's just a personal preference of mine. This way, the conditions are nicely lined up (which is particularly useful here as most conditions are very similar). And I feel like the comments are nicer -- I always struggle to comment the condition on an `else if` (where to put the comment?!). I use `match () { ... }` from time to time, but I also saw it in other people's Rust code already.

Note though that this parsing code is not optimized yet or anything. It surely could be better, both in performance and readability.

**Comment by lukaslueg** [comment]
Thanks
