### ISSUE TITLE
Add `format!` macro to create a termcolor::Buffer

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/bunt#2]
The slight "problem" is that in order to create a `Buffer`, we probably want to go through `BufferWriter`. And there again we have to specify a color preference, where we would also default to `Auto`, I guess.

**Comment by LukasKalbertodt** [comment]
So the bigger problem is that a `Buffer` has a specific format (ansi, Windows console, ...) already. That format depends on the platform, but also on runtime values: on Windows, it is checked at runtime whether there is a Windows console. In `format!` I would have to arbitrarily chose between stdout and stderr to get that information. And of course, in rare situations, the answer for both of these streams might be different! 

Most users would probably interpret a `bunt::format!` API such that it's fine to print the returned buffer on both, stderr and stdout. But that's not necessarily true. So I actually think I'd rather not add `format!`. It is always possible to `write!` into an existing buffer.

**Comment by BurntSushi** [comment]
Yeah, this is _the_ fundamental thing that differentiates termcolor from more ergonomic libraries that only work with ANSI escapes.

**Comment by LukasKalbertodt** [comment]
It should be possible to implement this by using a platform-independent encoding/format in `Buffer` and then converting it to the target encoding only when printing it. But that's probably a lot of work and also slower in many cases. Though I don't even know how you store the Windows console API calls in `Buffer`. I should take a look at that.

**Comment by BurntSushi** [comment]
Right. Another approach is to write an ANSI interpreter that runs on Windows only. That is, it translates ANSI escape codes on the fly. That way, it's zero cost when using actual ANSI escapes.

To be honest, that's probably the best approach. What I did was just simpler, but I think termcolor could evolve to have an ANSI interpreter without breaking backcompat (since Buffer is so limited).

**Comment by LukasKalbertodt** [comment]
That's an interesting idea. Looking at your `WindowsBuffer::print`, interpreting ANSI escapes is probably not even that much slower. And of course, having slowdown on only one platform is better than having it on all platforms. 

I'd be somewhat interested in trying that out (also for the sake of having a `bunt::format`), but I don't have lots of free time to spare. Also, regarding backwards compatibility: there exists `Buffer::console` which would then not make a lot of sense.
