### ISSUE TITLE
Support omitting format string

### ISSUE THREAD

**Issue by andrewhickman** [LukasKalbertodt/bunt#23]
For example `println!()` or `writeln!(stream)` would just write a line break.

This mirrors the functionality of the std macros, making these more of a drop in replacement. Note the [write_with_newline](https://rust-lang.github.io/rust-clippy/master/#write_with_newline) clippy lint prefers this short form, which can be annoying since it also triggers when using `writeln` from this crate.

**Comment by LukasKalbertodt** [comment]
That's a good point. Not quite sure how I did not do that in the first place. 

This is fixed in the linked PR and released in 0.2.6.
